---
title: "Spatial Figures"
output: html_document
---
# Rashad Yusifov

## Problem 1


```{r problem_1_data,include=FALSE}

library(tidyverse)
library(maps)

####make some data for painting the map

my_world_map <- map_data("world")

countries <- unique(my_world_map$region)

set.seed(987)
some_data_values <- data.frame(

  "region"=countries,
  
  "Score"=runif(252,0,100))

```

```{r problem_1,echo=FALSE,message=FALSE}

####Make sure you install any necessary libraries

####HINT: Use the following code to get the colors right
#scale_fill_distiller(palette=5)

####HINT: make sure you use left_join to combine the data_values above to the world map data in my_world_map

map_data_combined <- left_join(my_world_map,some_data_values,by="region")

ggplot(data = map_data_combined, mapping = aes(x= long, y= lat, group = group, fill = Score))+geom_polygon() + scale_fill_distiller(palette=5)
```

## Problem 2



```{r problem_2_data,include=FALSE}

#####DO NOT MODIFY THIS CHUNK
set.seed(15)
Measurement<-rnorm(32,50,1)

```


```{r solution_p2,echo=FALSE,message=FALSE}

####Make sure you load any necessary libraries

####HINT: Use a filter command to get just maps of Costa Rica, Panama, and Nicaragua

####Hint: Use a filter command to put in points only for cities with a population of greater than 40,000. This should leave you with 32 cities.

####Hint: Use add_column to attach the "Measurement" variable to your data, and set that to the color aesthetic when you draw the points.

####Hint: set the colors for the city points with scale_color_distiller(palette=7)

####Hint: set the size of all points to the value 5

####let's pick just the big cities
cities <- filter(map_data_combined,region == "Costa Rica" | region == "Panama"|region == "Nicaragua")

my_cities <-maps::world.cities


my_big_cities <- filter(my_cities,country.etc == "Costa Rica" | country.etc == "Panama"|country.etc == "Nicaragua")

my_big_cities <- filter(my_big_cities,pop>40000)



cities_added <- my_big_cities %>% add_column(Measurement)

cities_added$region <- cities_added$country.etc




####make a point for every city
ggplot(data = cities, mapping = aes(x= long, y= lat, group = group)) +   
   geom_polygon(color="black",fill="white")  + geom_point(data = cities_added,aes(x=long,y=lat,group=NULL,  color = Measurement), size = 5) + scale_color_distiller(palette=7)

```

## Problem 3



```{r problem_3_data,include=FALSE}

#####INSTALL THESE PACKAGES IF NECESSARY
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)

####DO NOT MODIFY
s_america<-ne_countries(scale="medium",continent='south america',returnclass="sf")


??ne_countries
```

```{r problem3,echo=FALSE}

####Make sure you load any necessary libraries

####HINT: the s_america object created in the chunk above is a simple features object with many columns. Identify the correct column based on the solution figure and use it to color in the choropleth.

####HINT: Use scale_fill_distiller and palette 10 to the match the colors.


ggplot(s_america) +  geom_sf(aes(fill=pop_est)) +  scale_fill_distiller(palette=10)

```


